easy_admin:
    site_name: 'Eoskometa Corp.'
    design:
        brand_color: '#1ABC9C'
    entities:
        content:
            class: App\Entity\Content
        setting:
            class: App\Entity\Setting
        show:
            class: App\Entity\Show
            list:
                fields:
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.shows_images%', template: 'vich_uploader_image.html.twig' }
            show:
                fields:
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'image', type: 'image', base_path: '%app.path.shows_images%' }
            form:
                fields:
                    - { property: 'title' }
                    - { property: 'text' }
                    - { property: 'imageFile', type: 'vich_image' }
        dogs:
            class: App\Entity\Dog
            list:
                fields:
                    - { property: 'name' }
                    - { property: 'gender' }
                    - { property: 'image', type: 'image', base_path: '%app.path.dogs_images%', template: 'vich_uploader_image.html.twig' }
            show:
                fields:
                    - { property: 'name' }
                    - { property: 'gender' }
                    - { property: 'gang' }
                    - { property: 'about' }
                    - { property: 'image', type: 'image', base_path: '%app.path.dogs_images%' }
            form:
                fields:
                    - { property: 'name' }
                    - { property: 'gender' }
                    - { property: 'gang' }
                    - { property: 'about' }
                    - { property: 'imageFile', type: 'vich_image' }
